services:
  watchtower:
      image: containrrr/watchtower
      command:
        - "--label-enable"
        - "--interval"
        - "30"
        - "--rolling-restart"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "7642:80"
    depends_on:
      - server
    networks:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: ghcr.io/kmutt-cpe-student/comcamp36-server:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ub.rule=Host(`api.comcamp.io`)"
      - "traefik.http.services.ub.loadbalancer.server.port=4000"
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - main

networks:
  main:
    driver: bridge