import { z } from "zod";

export const questionFormSchema = z.object({
  question1: z.number(),
  question2: z.number(),
  question3: z.number(),
  question4: z.number(),
  question5: z.number(),
  question6: z.number(),
  question7: z.number(),
  question8: z.number(),
  question9: z.number(),
  question10: z.number(),
  question11: z.number(),
  question12: z.number(),
  question13: z.number(),
  question14: z.number(),
  question15: z.number(),
  question16: z.number(),
  question17: z.number(),
  question18: z.number(),
  question19: z.number(),
  question20: z.number(),
  question21: z.number(),
  question22: z.number(),
  question23: z.number(),
  question24: z.number(),
  question25: z.number(),
  question26: z.number(),
  question27: z.number(),
  question28: z.number(),
  question29: z.number(),
  question30: z.number(),
});
