#!/bin/bash

colors=(
  "\033[31m" # Red
  "\033[33m" # Yellow
  "\033[32m" # Green
  "\033[36m" # Cyan
  "\033[34m" # Blue
  "\033[35m" # Magenta
)

reset="\033[0m"

i=0
while IFS= read -r line; do
  printf "%b%s%b\n" "${colors[i % ${#colors[@]}]}" "$line" "$reset"
  ((i++))
done < "$(dirname "$0")/icon.txt"

pnpm lint-staged
